# Project language
language: php

# Allows use container-based infrastructure
sudo: false

# Start mysql service
#services:
#  - mysql

# Cache composer packages so "composer install" is faster
cache:
  directories:
    - $HOME/.composer/cache/files

matrix:
  fast_finish: true
  include:
    - php: 7.4
    - php: 8.0
  allow_failures:
    - php: hhvm

before-install:
  - composer self-update

# Install composer dependencies,
# Create database, schema and fixtures
install:
  - composer install
  - wget -c -nc --retry-connrefused --tries=0 https://github.com/php-coveralls/php-coveralls/releases/download/v2.0.0/php-coveralls.phar
  - chmod +x php-coveralls.phar
  - php php-coveralls.phar --version

# Run script
script:
  - phpunit --coverage-clover build/logs/clover.xml
  - composer cs-check
  - composer analyze

after_success:
  - travis_retry php php-coveralls.phar -v
