language: php

os:
  - linux

git:
  depth: 1

php:
  - 7.1

install:
  - travis_retry composer install --no-interaction

script:
  - ./vendor/bin/phpunit tests/

branches:
  only: master

notifications:
  email:
    on_success: never
    on_failure: always